# [최종 수정] docker-compose.yml

services:
  # 1. Node.js 서비스 정의
  nodejs-app:
    container_name: attention-nodejs
    image: hwengdeong/attention-app:latest
    ports:
      - "3000:3000"
    restart: always
    networks:
      - attention-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # 2. Redis 서비스 정의
  redis:
    container_name: attention-redis
    image: "redis:alpine"
    restart: always
    networks:
      - attention-network

networks:
  attention-network:
    driver: bridge