services:
  nodejs-app:
    container_name: attention-nodejs
    image: hwengdeong/attention-app:latest
    ports:
      - "3000:3000"
    restart: always
    networks:
      - attention-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    container_name: attention-redis
    image: "redis:alpine"
    restart: always
    networks:
      - attention-network

  session-data-saver:
    container_name: attention-data-saver
    image: hwengdeong/attention-data-saver:latest
    restart: always
    networks:
      - attention-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./dataStorage:/app/saved_data

  websocket:
    container_name: attention-websocket
    # image: hwengdeong/attention-websocket:latest  # <- 이 줄을 주석 처리하거나 삭제
    build: .                                    # <- 이 줄을 추가 (Dockerfile이 현재 폴더에 있다고 가정)
    ports:
      - "9001:9001"
    restart: always
    networks:
      - attention-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  attention-network:
    driver: bridge
