name: push and deploy
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: push with shell files
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          port: ${{ secrets.NODEJS_PORT }}
          script: |
            ./deploy.sh