[package]
name = "websocket"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.23.1"
futures-util = "0.3.30"
redis = { version = "0.25.3", features = ["tokio-comp"] }