name: Docker CI/CD for Attention App

on:
  push:
    branches:
      

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push nodejs-app image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/attention-app:latest

      - name: Build and push websocket image
        uses: docker/build-push-action@v5
        with:
          context: ./websocket
          file: ./websocket/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/attention-websocket:latest

      - name: Build and push datasaver image
        uses: docker/build-push-action@v5
        with:
          context: ./sessionDataSave 
          file: ./sessionDataSave/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/attention-data-saver:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd /work/attention
            export MONGO_HOST=${{ secrets.MONGO_HOST }}
            export MONGO_PORT=${{ secrets.MONGO_PORT }}
            export MONGO_USER=${{ secrets.MONGO_USER }}
            export MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
            export MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}
            DOCKERHUB_USER=${{ secrets.DOCKERHUB_USERNAME }}
            
            docker login -u $DOCKERHUB_USER -p ${{ secrets.DOCKERHUB_TOKEN }}
            
            docker pull $DOCKERHUB_USER/attention-app:latest
            docker pull $DOCKERHUB_USER/attention-websocket:latest
            docker pull $DOCKERHUB_USER/attention-data-saver:latest
            docker system prune -a -f
            docker compose up -d --remove-orphans
