name: Deploy to EC2 with all repo content

on:
  push:
    branches:
      - main

env:
  AWS_HOST: ${{ secrets.AWS_HOST }}
  AWS_KEY: ${{ secrets.AWS_KEY }}
  AWS_USER: ${{ secrets.AWS_USER }}
  SSH_PORT: ${{ secrets.SSH_PORT }}

jobs:
  deploy:
    name: Build and Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Create tarball of repository
        run: |
          tar -czf ../repository.tar.gz --exclude='./.git' .

      # 1. [변경] scp-action을 사용하여 파일을 EC2로 전송
      - name: Transfer tarball to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.AWS_HOST }}
          username: ${{ env.AWS_USER }}
          key: ${{ env.AWS_KEY }}
          port: ${{ env.SSH_PORT }}
          source: "../repository.tar.gz"
          target: "/tmp" # EC2의 /tmp 디렉토리에 파일을 전송

      # 2. [변경] ssh-action을 사용하여 원격지에서 명령어 실행
      - name: Extract tarball and setup permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.AWS_HOST }}
          username: ${{ env.AWS_USER }}
          key: ${{ env.AWS_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            rm -rf /root/deploy
            mkdir -p /root/deploy
            tar -xzf /tmp/repository.tar.gz -C /root/deploy/
            rm /tmp/repository.tar.gz
            chmod +x /root/deploy/sh/deploy.sh
            chmod 755 /root/deploy/sh
            chmod 755 /root/deploy
          debug: true

      # 3. 기존과 동일하게 배포 스크립트 실행
      - name: Execute remote deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.AWS_HOST }}
          username: ${{ env.AWS_USER }}
          key: ${{ env.AWS_KEY }}
          port: ${{ env.SSH_PORT }}
          script_path: "/root/deploy/sh/deploy.sh"
          debug: true