name: Deploy to EC2 with all repo content

on:
  push:
    branches:
      - main

env:
  AWS_HOST: ${{ secrets.AWS_HOST }}
  AWS_KEY: ${{ secrets.AWS_KEY }}
  AWS_USER: ${{ secrets.AWS_USER }}
  SSH_PORT: ${{ secrets.SSH_PORT }}

jobs:
  deploy:
    name: Build and Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4 

      - name: Create tarball of repository # 레포지토리 내용을 .tar.gz 파일로 압축
        run: |
          # --exclude 옵션의 위치를 tar 명령 바로 뒤로 옮깁니다.
          tar -czf repository.tar.gz --exclude='./.git' . 
        # 이 스텝이 실행되면 GitHub Actions 가상 머신의 현재 작업 디렉토리에
        # repository.tar.gz 파일이 생성됩니다.

      - name: Transfer tarball and extract on EC2 # 압축 파일 전송 및 해제
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ env.AWS_HOST }}
          username: ${{ env.AWS_USER }}
          key: ${{ env.AWS_KEY }}
          port: ${{ env.SSH_PORT }}
          source: "repository.tar.gz" 
          target: "/tmp/repository.tar.gz"
          script: |
            rm -rf /root/deploy
            mkdir -p /root/deploy
            tar -xzf /tmp/repository.tar.gz -C /root/deploy/
            rm /tmp/repository.tar.gz
            chmod +x /root/deploy/sh/deploy.sh
            chmod 755 /root/deploy/sh
            chmod 755 /root/deploy
          debug: true 

      - name: Execute remote deployment script # EC2에서 deploy.sh 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.AWS_HOST }}
          username: ${{ env.AWS_USER }}
          key: ${{ env.AWS_KEY }}
          port: ${{ env.SSH_PORT }}
          script_path: "/root/deploy/sh/deploy.sh" 
          debug: true