name: push and deploy
on: 
  push:
    branches:
      - main

env:
  AWS_HOST: ${{ secrets.AWS_HOST }}
  AWS_KEY: ${{ secrets.AWS_KEY }}
  AWS_USER: ${{ secrets.AWS_USER }}
  SSH_PORT: ${{ secrets.SSH_PORT }} 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy with shell script
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ env.AWS_HOST }}
          username: ${{ env.AWS_USER }}
          key: ${{ env.AWS_KEY }}

          port: ${{ env.SSH_PORT }} 
          source: "./sh/deploy.sh"
          target: "/tmp/deploy_script.sh" 
          
          script: |
            chmod +x /tmp/deploy_script.sh
            /tmp/deploy_script.sh
            rm /tmp/deploy_script.sh