name: Deploy to EC2 with all repo content

on:
  push:
    branches:
      - main

env:
  AWS_HOST: ${{ secrets.AWS_HOST }}
  AWS_KEY: ${{ secrets.AWS_KEY }}
  AWS_USER: ${{ secrets.USERNAME }} 
  SSH_PORT: ${{ secrets.SSH_PORT }} 

jobs:
  deploy:
    name: Build and Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4 

      - name: Copy entire repository to EC2 /root/deploy
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ env.AWS_HOST }}
          username: ${{ env.AWS_USER }}
          key: ${{ env.AWS_KEY }}
          port: ${{ env.SSH_PORT }}
          source: "./"
          target: "/root/deploy/"
          sync: true
          debug: true 

      - name: Set permissions for deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.AWS_HOST }}
          username: ${{ env.AWS_USER }}
          key: ${{ env.AWS_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            chmod +x /root/deploy/sh/deploy.sh
            chmod 755 /root/deploy/sh # sh 폴더
            chmod 755 /root/deploy   # deploy 폴더 (만약 AWS_USER가 root가 아니라면 필요)
          debug: true

      - name: Execute remote deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.AWS_HOST }}
          username: ${{ env.AWS_USER }}
          key: ${{ env.AWS_KEY }}
          port: ${{ env.SSH_PORT }}
          script_path: "/root/deploy/sh/deploy.sh" 